CREATE TABLE "seed_film_tag_baseline" (
	"film_slug" text NOT NULL,
	"tag_slug" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "seed_film_tag_baseline_film_slug_tag_slug_pk" PRIMARY KEY("film_slug","tag_slug")
);
--> statement-breakpoint
CREATE TABLE "seed_tag_baseline" (
	"slug" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- Bootstrap (hand-written, not generated by drizzle-kit).
--
-- The baseline records what seed-data last asked for. On a database that
-- already holds content there is no such record, so seed it from what is
-- there now: "whatever this database currently has, treat as previously
-- seeded". Without this, every existing tag would read as an addition the
-- next release is making, and the seeder would re-apply the whole corpus.
--
-- On an empty database both statements insert nothing, which is correct —
-- a fresh install has no history, so everything genuinely is new.
--
-- One-time blind spot, by construction: a tag an editor removed BEFORE
-- this migration cannot be seen here and will be re-applied once. Verify
-- the target's tags/junctions match seed-data before migrating a database
-- where that may have happened.
INSERT INTO "seed_tag_baseline" ("slug")
	SELECT "slug" FROM "tags"
	ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO "seed_film_tag_baseline" ("film_slug", "tag_slug")
	SELECT f."slug", t."slug"
	FROM "film_tags" ft
	JOIN "films" f ON f."id" = ft."film_id"
	JOIN "tags" t ON t."id" = ft."tag_id"
	ON CONFLICT DO NOTHING;
