import { MONOGRAM } from "@/assets/brand/monogram-paths";

/**
 * Inline 8½ monogram, drawn from the path data generated by
 * scripts/generate-brand-assets.ts (same source as the favicon set).
 * Decorative and locale-agnostic: it sits inside the home link whose
 * accessible name stays 八部半, so it carries no label of its own.
 * The frame uses a non-scaling 1px stroke to match the site's hairline
 * borders at any rendered size — the asset's own 3/512 stroke would be
 * sub-pixel mush at header scale.
 */
export function BrandMark({ className }: { className?: string }) {
  const canvas = Number(MONOGRAM.viewBox.split(" ")[2]);
  const { inset, stroke } = MONOGRAM.frame;
  return (
    <svg viewBox={MONOGRAM.viewBox} aria-hidden="true" className={className}>
      <rect
        x={inset}
        y={inset}
        width={canvas - 2 * inset}
        height={canvas - 2 * inset}
        fill="none"
        stroke={stroke}
        strokeWidth={1}
        vectorEffect="non-scaling-stroke"
      />
      {MONOGRAM.glyphs.map((g) => (
        <path key={g.fill} d={g.d} fill={g.fill} />
      ))}
    </svg>
  );
}
